apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - db.yaml
  - ../base

secretGenerator:
- name: secrets-env
  envs:
  - .env

- name: config-files
  files:
    - rsa.private.key
    - rsa.public.key
