apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-

resources:
  - ../base

patches:
  - path: user-service.yml

secretGenerator:
- name: secrets-env
  envs:
  - .env
  - .env.public

- name: config-files
  files:
  - rsa.private.key
  - rsa.public.key
