namePrefix: prod-

bases:
  - ../base

patchesStrategicMerge:
  - user-service.yml

secretGenerator:
- name: secrets-env
  envs:
  - .env

- name: config-files
  files:
  - rsa.private.key
  - rsa.public.key
