apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: hulkdx/ff-user:v1
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: secrets-env
          volumeMounts:
          - mountPath: /config
            name: config-files
      volumes:
      - name: config-files
        secret:
          secretName: config-files
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 8080
      targetPort: 8080
